"""change schedule uniquie fields

Revision ID: 1fce2fed11dd
Revises: d1ff39e81e8e
Create Date: 2018-08-17 09:14:14.924498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fce2fed11dd'
down_revision = 'd1ff39e81e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Schedules', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Schedules', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Schedules', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Schedules', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('Schedules', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Schedules', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('Schedules', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Schedules', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('Schedules', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Schedules', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
