"""add schedule_id

Revision ID: 60b8ecc47e62
Revises: b4f42d3abaaa
Create Date: 2018-08-20 10:35:20.119634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b8ecc47e62'
down_revision = 'b4f42d3abaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ScheduleDetails')
    op.add_column('SCHDetails', sa.Column('schedule_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'SCHDetails', 'Schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SCHDetails', type_='foreignkey')
    op.drop_column('SCHDetails', 'schedule_id')
    op.create_table('ScheduleDetails',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ScheduleDetails_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sch_detail_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sch_detail_id'], ['SCHDetails.id'], name='ScheduleDetails_sch_detail_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_id'], ['Schedules.id'], name='ScheduleDetails_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ScheduleDetails_pkey'),
    sa.UniqueConstraint('schedule_id', 'sch_detail_id', name='ScheduleDetails_schedule_id_sch_detail_id_key')
    )
    # ### end Alembic commands ###
