"""customer

Revision ID: 74651848a6ba
Revises: 9368f76463be
Create Date: 2018-09-19 13:36:20.957320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74651848a6ba'
down_revision = '9368f76463be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('Customers', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('Customers', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('Customers', sa.Column('login', sa.String(length=100), nullable=False))
    op.add_column('Customers', sa.Column('password', sa.String(length=100), nullable=False))
    op.alter_column('Customers', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('Customers_email_key', 'Customers', type_='unique')
    op.drop_constraint('Customers_email_phone_key', 'Customers', type_='unique')
    op.create_unique_constraint(None, 'Customers', ['login'])
    op.create_unique_constraint(None, 'Customers', ['login', 'email'])
    op.create_foreign_key(None, 'Customers', 'Cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'Customers', 'Countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Customers', type_='foreignkey')
    op.drop_constraint(None, 'Customers', type_='foreignkey')
    op.drop_constraint(None, 'Customers', type_='unique')
    op.drop_constraint(None, 'Customers', type_='unique')
    op.create_unique_constraint('Customers_email_phone_key', 'Customers', ['email', 'phone'])
    op.create_unique_constraint('Customers_email_key', 'Customers', ['email'])
    op.alter_column('Customers', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('Customers', 'password')
    op.drop_column('Customers', 'login')
    op.drop_column('Customers', 'description')
    op.drop_column('Customers', 'country_id')
    op.drop_column('Customers', 'city_id')
    # ### end Alembic commands ###
