"""add phone & email confirm fields

Revision ID: 795c07883dfc
Revises: 1fce2fed11dd
Create Date: 2018-08-17 10:43:54.646251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795c07883dfc'
down_revision = '1fce2fed11dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email_confirm', sa.Boolean(), nullable=True))
    op.add_column('Users', sa.Column('phone_confirm', sa.Boolean(), nullable=True))
    op.alter_column('Users', 'login',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'login',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('Users', 'phone_confirm')
    op.drop_column('Users', 'email_confirm')
    # ### end Alembic commands ###
