"""add creater_id

Revision ID: 82ead8ff059e
Revises: 795c07883dfc
Create Date: 2018-08-20 09:23:56.868767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ead8ff059e'
down_revision = '795c07883dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserSchedules')
    op.add_column('Schedules', sa.Column('creater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Schedules', 'Users', ['creater_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Schedules', type_='foreignkey')
    op.drop_column('Schedules', 'creater_id')
    op.create_table('UserSchedules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"UserSchedules_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['Schedules.id'], name='UserSchedules_schedule_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='UserSchedules_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='UserSchedules_pkey'),
    sa.UniqueConstraint('user_id', 'schedule_id', name='UserSchedules_user_id_schedule_id_key')
    )
    # ### end Alembic commands ###
