"""fix schedule_id key

Revision ID: a4fc52c2c575
Revises: 60b8ecc47e62
Create Date: 2018-08-20 14:59:46.305447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fc52c2c575'
down_revision = '60b8ecc47e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SCHDetails_schedule_id_fkey', 'SCHDetails', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('SCHDetails_schedule_id_fkey', 'SCHDetails', 'Schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###
