"""fix creater_id

Revision ID: b4f42d3abaaa
Revises: 82ead8ff059e
Create Date: 2018-08-20 09:53:17.526280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f42d3abaaa'
down_revision = '82ead8ff059e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Schedules', 'creater_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Schedules', 'creater_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
