"""add fields

Revision ID: e0aee49e7ef2
Revises: ef808564c9b7
Create Date: 2018-09-05 10:06:59.487429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0aee49e7ef2'
down_revision = 'ef808564c9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('Customers', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('Customers', sa.Column('email_confirm', sa.Boolean(), nullable=True))
    op.add_column('Customers', sa.Column('flags', sa.Integer(), nullable=True))
    op.add_column('Customers', sa.Column('mail_agreement', sa.Boolean(), nullable=True))
    op.add_column('Customers', sa.Column('phone_confirm', sa.Boolean(), nullable=True))
    op.add_column('Schedules', sa.Column('activate', sa.Boolean(), nullable=False))
    op.drop_column('Schedules', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Schedules', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('Schedules', 'activate')
    op.drop_column('Customers', 'phone_confirm')
    op.drop_column('Customers', 'mail_agreement')
    op.drop_column('Customers', 'flags')
    op.drop_column('Customers', 'email_confirm')
    op.drop_column('Customers', 'data')
    op.drop_column('Customers', 'address')
    # ### end Alembic commands ###
