"""delete cascade

Revision ID: e13242ea6a0f
Revises: e0aee49e7ef2
Create Date: 2018-09-08 05:11:12.901408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13242ea6a0f'
down_revision = 'e0aee49e7ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Orders_schedule_id_fkey', 'Orders', type_='foreignkey')
    op.create_foreign_key(None, 'Orders', 'Schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('SCHDetails_schedule_id_fkey', 'SCHDetails', type_='foreignkey')
    op.create_foreign_key(None, 'SCHDetails', 'Schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.add_column('Schedules', sa.Column('data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Schedules', 'data')
    op.drop_constraint(None, 'SCHDetails', type_='foreignkey')
    op.create_foreign_key('SCHDetails_schedule_id_fkey', 'SCHDetails', 'Schedules', ['schedule_id'], ['id'])
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.create_foreign_key('Orders_schedule_id_fkey', 'Orders', 'Schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###
