"""fix customer

Revision ID: ef808564c9b7
Revises: 950e90775691
Create Date: 2018-09-03 14:41:15.390729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef808564c9b7'
down_revision = '950e90775691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CustomerOrders')
    op.create_unique_constraint(None, 'Customers', ['email'])
    op.add_column('Orders', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.alter_column('Orders', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Orders', 'Customers', ['customer_id'], ['id'])
    op.alter_column('SCHDetails', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SCHDetails', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.alter_column('Orders', 'schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Orders', 'customer_id')
    op.drop_constraint(None, 'Customers', type_='unique')
    op.create_table('CustomerOrders',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"CustomerOrders_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], name='CustomerOrders_customer_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], name='CustomerOrders_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='CustomerOrders_pkey'),
    sa.UniqueConstraint('customer_id', 'order_id', name='CustomerOrders_customer_id_order_id_key')
    )
    # ### end Alembic commands ###
